# Generated by Django 2.2 on 2021-04-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fssp', '0005_remove_request_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fssp.Request'),
        ),
    ]
