# Generated by Django 2.1.4 on 2018-12-18 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjudication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Решение',
            },
        ),
        migrations.CreateModel(
            name='ADRecord',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionaries.Document')),
                ('ad_type', models.IntegerField(default=0)),
                ('protocol_date', models.DateField(null=True, verbose_name='Дата простокола')),
                ('referring_to_instance_date', models.DateField(null=True, verbose_name='Дата направления в инстанцию')),
                ('adjudication_amount_of_fine', models.IntegerField(default=0, verbose_name='Размер штрафа')),
                ('adjudication_date', models.DateField(null=True, verbose_name='Дата вынесения решения')),
                ('adjudication_start_date', models.DateField(null=True, verbose_name='Дата вступления в силу')),
                ('date_of_receipt_unlegal', models.DateField(null=True, verbose_name='Дата поступления постан не вступившего в законную силу')),
                ('date_of_receipt_legal', models.DateField(null=True, verbose_name='Дата поступления постан вступившего в законную силу')),
                ('publish_gisgkh_date', models.DateField(null=True, verbose_name='Дата публикации в ГИС ЖКХ')),
                ('publish_erp_date', models.DateField(null=True, verbose_name='Дата публикации в ЕРП')),
                ('box_number', models.CharField(default='', max_length=500, null=True, verbose_name='Номер коробки в архиве')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('has_appeal', models.BooleanField(default=False, verbose_name='Имеет обжалование')),
            ],
            options={
                'verbose_name': 'Запись АД',
            },
            bases=('dictionaries.document',),
        ),
        migrations.CreateModel(
            name='ADStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500, null=True)),
                ('short_text', models.CharField(default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Стадия исп. произв.',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionaries.Document')),
                ('is_forced', models.BooleanField(default=False, verbose_name='Принудительная оплата')),
                ('payment_date', models.DateField(null=True, verbose_name='Дата оплаты')),
                ('payment_amount', models.IntegerField(default=0, verbose_name='Сумма оплаты')),
                ('referring_to_instance_date', models.DateField(null=True, verbose_name='Дата направления в инстанцию')),
                ('execution_number', models.CharField(default='', max_length=500, null=True, verbose_name='Номер исполнительного производства')),
                ('execution_date', models.DateField(null=True, verbose_name='Дата исполнительного производства')),
                ('execution_stop_date', models.DateField(null=True, verbose_name='Дата окончания исполнительного производства')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Запись исполнительного производства',
            },
            bases=('dictionaries.document',),
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Результат исп производства',
            },
        ),
        migrations.CreateModel(
            name='HistoricalADRecord',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=500, verbose_name='номер документа')),
                ('doc_date', models.DateField(verbose_name='дата документа')),
                ('doc_type', models.CharField(default='', max_length=500, null=True, verbose_name='тип документа')),
                ('root_id', models.IntegerField(default=0, editable=False, verbose_name='root_id')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('ad_type', models.IntegerField(default=0)),
                ('protocol_date', models.DateField(null=True, verbose_name='Дата простокола')),
                ('referring_to_instance_date', models.DateField(null=True, verbose_name='Дата направления в инстанцию')),
                ('adjudication_amount_of_fine', models.IntegerField(default=0, verbose_name='Размер штрафа')),
                ('adjudication_date', models.DateField(null=True, verbose_name='Дата вынесения решения')),
                ('adjudication_start_date', models.DateField(null=True, verbose_name='Дата вступления в силу')),
                ('date_of_receipt_unlegal', models.DateField(null=True, verbose_name='Дата поступления постан не вступившего в законную силу')),
                ('date_of_receipt_legal', models.DateField(null=True, verbose_name='Дата поступления постан вступившего в законную силу')),
                ('publish_gisgkh_date', models.DateField(null=True, verbose_name='Дата публикации в ГИС ЖКХ')),
                ('publish_erp_date', models.DateField(null=True, verbose_name='Дата публикации в ЕРП')),
                ('box_number', models.CharField(default='', max_length=500, null=True, verbose_name='Номер коробки в архиве')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('has_appeal', models.BooleanField(default=False, verbose_name='Имеет обжалование')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ad_stage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ad.ADStage')),
                ('adjudication', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ad.Adjudication')),
                ('article', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Article')),
            ],
            options={
                'verbose_name': 'historical Запись АД',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExecution',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=500, verbose_name='номер документа')),
                ('doc_date', models.DateField(verbose_name='дата документа')),
                ('doc_type', models.CharField(default='', max_length=500, null=True, verbose_name='тип документа')),
                ('root_id', models.IntegerField(default=0, editable=False, verbose_name='root_id')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('is_forced', models.BooleanField(default=False, verbose_name='Принудительная оплата')),
                ('payment_date', models.DateField(null=True, verbose_name='Дата оплаты')),
                ('payment_amount', models.IntegerField(default=0, verbose_name='Сумма оплаты')),
                ('referring_to_instance_date', models.DateField(null=True, verbose_name='Дата направления в инстанцию')),
                ('execution_number', models.CharField(default='', max_length=500, null=True, verbose_name='Номер исполнительного производства')),
                ('execution_date', models.DateField(null=True, verbose_name='Дата исполнительного производства')),
                ('execution_stop_date', models.DateField(null=True, verbose_name='Дата окончания исполнительного производства')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('document_ptr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Document')),
            ],
            options={
                'verbose_name': 'historical Запись исполнительного производства',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, null=True, verbose_name='Наименование инстанции')),
                ('group', models.CharField(default='', max_length=20, null=True, verbose_name='Тип инстанции')),
                ('address', models.CharField(default='', max_length=500, null=True, verbose_name='Адрес')),
                ('oktmo', models.CharField(default='', max_length=20, null=True, verbose_name='ОКТМО')),
                ('email', models.CharField(default='', max_length=50, null=True, verbose_name='Почта')),
                ('telephone', models.CharField(default='', max_length=50, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Инстанция',
            },
        ),
        migrations.AddField(
            model_name='historicalexecution',
            name='enforcement_agent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ad.Instance'),
        ),
        migrations.AddField(
            model_name='historicalexecution',
            name='execution_result',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ad.ExecutionResult'),
        ),
        migrations.AddField(
            model_name='historicalexecution',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexecution',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Organization'),
        ),
        migrations.AddField(
            model_name='historicalexecution',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Document'),
        ),
        migrations.AddField(
            model_name='historicaladrecord',
            name='court',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ad.Instance'),
        ),
        migrations.AddField(
            model_name='historicaladrecord',
            name='document_ptr',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Document'),
        ),
        migrations.AddField(
            model_name='historicaladrecord',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladrecord',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Organization'),
        ),
        migrations.AddField(
            model_name='historicaladrecord',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Document'),
        ),
        migrations.AddField(
            model_name='execution',
            name='enforcement_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.Instance', verbose_name='Инстанция'),
        ),
        migrations.AddField(
            model_name='execution',
            name='execution_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.ExecutionResult', verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='ad_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.ADStage', verbose_name='Стадия рассмотрения административного дела'),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='adjudication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.Adjudication', verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.Article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.Instance', verbose_name='Инстанция'),
        ),
    ]
