# Generated by Django 2.1.4 on 2019-01-28 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20190117_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, null=True, verbose_name='Наименование суда')),
                ('address', models.CharField(default='', max_length=500, null=True, verbose_name='Адрес')),
                ('oktmo', models.CharField(default='', max_length=20, null=True, verbose_name='ОКТМО')),
                ('email', models.CharField(default='', max_length=50, null=True, verbose_name='Почта')),
                ('telephone', models.CharField(default='', max_length=50, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Суд',
            },
        ),
        migrations.RemoveField(
            model_name='execution',
            name='enforcement_agent',
        ),
        migrations.RemoveField(
            model_name='historicalexecution',
            name='enforcement_agent',
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.Court', verbose_name='Инстанция'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='court',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ad.Court'),
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
    ]
