# Generated by Django 2.1.4 on 2019-01-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_auto_20190128_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrecord',
            name='ad_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.ADStage', verbose_name='Стадия рассмотрения административного дела'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='adjudication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.Adjudication', verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='adjudication_amount_of_fine',
            field=models.IntegerField(blank=True, default=0, verbose_name='Размер штрафа'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='adjudication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вынесения решения'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='adjudication_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вступления в силу'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='box_number',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Номер коробки в архиве'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.Court', verbose_name='Инстанция'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='date_of_receipt_legal',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления постан вступившего в законную силу'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='date_of_receipt_unlegal',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления постан не вступившего в законную силу'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='has_appeal',
            field=models.BooleanField(blank=True, default=False, verbose_name='Имеет обжалование'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='protocol_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата протокола'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='publish_erp_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации в ЕРП'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='publish_gisgkh_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации в ГИС ЖКХ'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='referring_to_instance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата направления в инстанцию'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='ad_stage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ad.ADStage', verbose_name='Стадия рассмотрения административного дела'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='adjudication',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ad.Adjudication', verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='adjudication_amount_of_fine',
            field=models.IntegerField(blank=True, default=0, verbose_name='Размер штрафа'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='adjudication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вынесения решения'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='adjudication_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вступления в силу'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='article',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='box_number',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Номер коробки в архиве'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='court',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ad.Court', verbose_name='Инстанция'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='date_of_receipt_legal',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления постан вступившего в законную силу'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='date_of_receipt_unlegal',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления постан не вступившего в законную силу'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='document_ptr',
            field=models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='dictionaries.Document'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='has_appeal',
            field=models.BooleanField(blank=True, default=False, verbose_name='Имеет обжалование'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='protocol_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата протокола'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='publish_erp_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации в ЕРП'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='publish_gisgkh_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации в ГИС ЖКХ'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='referring_to_instance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата направления в инстанцию'),
        ),
        migrations.AlterField(
            model_name='historicalexecution',
            name='document_ptr',
            field=models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='dictionaries.Document'),
        ),
        migrations.AlterField(
            model_name='historicalexecution',
            name='execution_result',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ad.ExecutionResult', verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='historicalexecution',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Organization', verbose_name='Организация'),
        ),
    ]
