# Generated by Django 2.1.4 on 2019-03-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0017_officer'),
        ('ad', '0004_auto_20190129_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, null=True, verbose_name='Наименование суда')),
                ('address', models.CharField(default='', max_length=500, null=True, verbose_name='Адрес')),
                ('oktmo', models.CharField(default='', max_length=20, null=True, verbose_name='ОКТМО')),
                ('email', models.CharField(default='', max_length=50, null=True, verbose_name='Почта')),
                ('telephone', models.CharField(default='', max_length=50, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Суд',
            },
        ),
        migrations.AddField(
            model_name='adrecord',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.User', verbose_name='инспектор'),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.Officer', verbose_name='должностное лицо'),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='uin',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ОКТМО'),
        ),
        migrations.AddField(
            model_name='historicaladrecord',
            name='inspector',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.User', verbose_name='инспектор'),
        ),
        migrations.AddField(
            model_name='historicaladrecord',
            name='officer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Officer', verbose_name='должностное лицо'),
        ),
        migrations.AddField(
            model_name='historicaladrecord',
            name='uin',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ОКТМО'),
        ),
        migrations.AddField(
            model_name='execution',
            name='fssp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.FSSP', verbose_name='ФССП'),
        ),
        migrations.AddField(
            model_name='historicalexecution',
            name='fssp',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ad.FSSP', verbose_name='ФССП'),
        ),
    ]
