# Generated by Django 2.1.4 on 2019-03-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_auto_20190318_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrecord',
            name='uin',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='УИН'),
        ),
        migrations.AlterField(
            model_name='historicaladrecord',
            name='uin',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='УИН'),
        ),
    ]
