# Generated by Django 2.1.4 on 2019-02-06 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_auto_20190205_0852'),
        ('analytic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractItemCountInReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField(verbose_name='имя модели справочника')),
                ('object_id', models.IntegerField(verbose_name='id элемента справочкинка')),
                ('count', models.IntegerField(default=0, verbose_name='количество')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField(blank=True, null=True, verbose_name='Начало отчетного периода')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Окончание отчетного периода')),
                ('month', models.IntegerField(default=0, verbose_name='Месяц')),
                ('year', models.IntegerField(default=0, verbose_name='Год')),
                ('houses_total_area', models.IntegerField(default=0, verbose_name='Площадь обследованных МКД и жилых домов')),
                ('houses_plan_area', models.IntegerField(default=0, verbose_name='Площадь обследованных МКД и жилых домов в результате плановых проверок')),
                ('houses_precept_area', models.IntegerField(default=0, verbose_name='Площадь обследованных МКД и жилых домов в результате проверки исполнения предписаний')),
                ('houses', models.IntegerField(default=0, verbose_name='Количество обследованных МКД и жилых домов')),
                ('doc', models.IntegerField(default=0, verbose_name='Количество документарных проверок')),
                ('doc_plan', models.IntegerField(default=0, verbose_name='Количество документарных плановых проверок')),
                ('doc_appeals', models.IntegerField(default=0, verbose_name='Количество документарных проверок по обращениям граждан')),
                ('doc_prosecutor', models.IntegerField(default=0, verbose_name='Количество документарных проверок по требованию прокуратуры')),
                ('doc_oms', models.IntegerField(default=0, verbose_name='Количество документарных проверок в отношении органов местного самоуправления')),
                ('doc_precept', models.IntegerField(default=0, verbose_name='Количество документарных проверок исполнения предписания')),
                ('out', models.IntegerField(default=0, verbose_name='Количество выездных поверок')),
                ('out_plan', models.IntegerField(default=0, verbose_name='Количество выездных плановых поверок')),
                ('out_appeals', models.IntegerField(default=0, verbose_name='Количество выездных поверок по обращениям граждан')),
                ('out_prosecutor', models.IntegerField(default=0, verbose_name='Количество выездных поверок по требованию прокуратуры')),
                ('out_oms', models.IntegerField(default=0, verbose_name='Количество выездных поверок в отношении органов местного самоуправления')),
                ('out_physic', models.IntegerField(default=0, verbose_name='Количество выездных поверок в отношении физического лица')),
                ('out_order', models.IntegerField(default=0, verbose_name='Количество выездных поверок исполнения предписания')),
                ('overdue', models.IntegerField(default=0, verbose_name='Количество проверок, проведенных с нарушением срока')),
                ('overdue_doc', models.IntegerField(default=0, verbose_name='Количество документарных проверок, проведенных с нарушением срока')),
                ('overdue_out', models.IntegerField(default=0, verbose_name='Количество выездных проверок, проведенных с нарушением срока')),
                ('exec_doc', models.IntegerField(default=0, verbose_name='Количество составленных исполнительных документов')),
                ('act', models.IntegerField(default=0, verbose_name='Количество составленных актов')),
                ('precept', models.IntegerField(default=0, verbose_name='Количество составленных предписаний')),
                ('control_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.ControlKind', verbose_name='вид контроля')),
            ],
        ),
        migrations.CreateModel(
            name='ViolationInGeneralReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='количество нарушений выявлено')),
                ('count_to_remove', models.IntegerField(default=0, verbose_name='количество нарушений к устранению')),
                ('count_of_removed', models.IntegerField(default=0, verbose_name='количество нарушений по факту устранено')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytic.GeneralReport', verbose_name='Отчет')),
                ('violation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.ViolationType', verbose_name='тип нарушения')),
            ],
        ),
        migrations.AddField(
            model_name='abstractitemcountinreport',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytic.GeneralReport', verbose_name='Отчет'),
        ),
    ]
