# Generated by Django 2.1.4 on 2019-02-12 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0011_auto_20190206_0946'),
        ('analytic', '0002_auto_20190206_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalreport',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.Department', verbose_name='Отдел, по которому составляется отчет'),
        ),
        migrations.AddField(
            model_name='generalreport',
            name='report_status',
            field=models.TextField(blank=True, null=True, verbose_name='Статус формирования отчета'),
        ),
        migrations.AddField(
            model_name='generalreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.User', verbose_name='Сотрудник, запросивший отчет'),
        ),
    ]
