# Generated by Django 2.1.4 on 2019-02-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0003_auto_20190212_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalreport',
            name='total_inspections',
            field=models.IntegerField(default=0, verbose_name='Всего проверок'),
        ),
    ]
