# Generated by Django 2.1.4 on 2019-02-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0004_generalreport_total_inspections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalreport',
            old_name='out_order',
            new_name='out_precept',
        ),
    ]
