# Generated by Django 2.1.4 on 2019-02-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0005_auto_20190213_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalreport',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата составления отчета'),
        ),
    ]
