# Generated by Django 2.1.4 on 2019-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0006_generalreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractitemcountinreport',
            name='text',
            field=models.TextField(default='nothing', verbose_name='наименование элемента справочника'),
            preserve_default=False,
        ),
    ]
