# Generated by Django 2.1.4 on 2019-02-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0008_auto_20190213_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalreport',
            old_name='violations_count_of_removed',
            new_name='violation_count_of_removed',
        ),
        migrations.RenameField(
            model_name='generalreport',
            old_name='violations_count_to_remove',
            new_name='violation_count_to_remove',
        ),
    ]
