# Generated by Django 2.1.4 on 2019-02-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0009_auto_20190213_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalreport',
            name='doc_and_out',
            field=models.IntegerField(default=0, verbose_name='Количество документарных и выездных проверок'),
        ),
        migrations.AddField(
            model_name='generalreport',
            name='doc_and_out_appeals',
            field=models.IntegerField(default=0, verbose_name='Количество документарных и выездных проверок по обращениям граждан'),
        ),
        migrations.AddField(
            model_name='generalreport',
            name='doc_and_out_oms',
            field=models.IntegerField(default=0, verbose_name='Количество документарных и выездных проверок в отношении органов местного самоуправления'),
        ),
        migrations.AddField(
            model_name='generalreport',
            name='doc_and_out_plan',
            field=models.IntegerField(default=0, verbose_name='Количество документарных и выездных плановых проверок'),
        ),
        migrations.AddField(
            model_name='generalreport',
            name='doc_and_out_precept',
            field=models.IntegerField(default=0, verbose_name='Количество документарных и выездных проверок исполнения предписания'),
        ),
        migrations.AddField(
            model_name='generalreport',
            name='doc_and_out_prosecutor',
            field=models.IntegerField(default=0, verbose_name='Количество документарных и выездных проверок по требованию прокуратуры'),
        ),
    ]
