# Generated by Django 2.1.4 on 2019-03-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0011_generalreport_executed_precept'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportresult',
            options={'verbose_name': 'Экспорт в Excel'},
        ),
        migrations.AlterModelOptions(
            name='generalreport',
            options={'verbose_name': 'Ежемесячный отчет'},
        ),
    ]
