# Generated by Django 2.2 on 2019-04-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0012_auto_20190328_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalreport',
            old_name='user',
            new_name='owner',
        ),
    ]
