# Generated by Django 2.2 on 2019-04-26 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0022_auto_20190426_1228'),
        ('analytic', '0013_auto_20190426_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalreport',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspector', to='dictionaries.User', verbose_name='Сотрудник, по которому составляется отчет'),
        ),
        migrations.AlterField(
            model_name='generalreport',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='dictionaries.User', verbose_name='Сотрудник, запросивший отчет'),
        ),
    ]
