# Generated by Django 2.1.4 on 2019-01-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_date',
            field=models.DateField(blank=True, verbose_name='дата документа'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='doc_date',
            field=models.DateField(blank=True, verbose_name='дата документа'),
        ),
    ]
