# Generated by Django 2.1.4 on 2019-01-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_auto_20190124_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='org_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.OrganizationType', verbose_name='Тип организации'),
        ),
    ]
