# Generated by Django 2.1.4 on 2019-01-30 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_auto_20190129_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='files',
            field=models.ManyToManyField(blank=True, to='dictionaries.File', verbose_name='файлы'),
        ),
        migrations.AddField(
            model_name='organization',
            name='files',
            field=models.ManyToManyField(blank=True, to='dictionaries.File', verbose_name='файлы'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='inn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='is_bankrupt',
            field=models.BooleanField(blank=True, default=False, verbose_name='Банкрот'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='kpp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='location_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес места нахождения'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_bankrupt',
            field=models.BooleanField(blank=True, default=False, verbose_name='Банкрот'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес места нахождения'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.OrganizationType', verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
