# Generated by Django 2.1.4 on 2019-01-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0006_auto_20190130_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouse',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='house',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий'),
        ),
    ]
