# Generated by Django 2.1.4 on 2019-02-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0010_auto_20190206_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department_old',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department_rp',
        ),
    ]
