# Generated by Django 2.1.4 on 2019-02-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0011_auto_20190206_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhouse',
            name='agr_conclusion_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата заключения договора'),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='changing_doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='основание для изменения: дата документа'),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='changing_doc_header',
            field=models.CharField(max_length=500, null=True, verbose_name='основание для изменения: заголовок документа'),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='changing_doc_number',
            field=models.CharField(max_length=500, null=True, verbose_name='основание для изменения: номер документа'),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='changing_org_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата смены организации в реестре'),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='exclusion_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата исключения из реестра'),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='exclusion_legal_basis',
            field=models.CharField(max_length=500, null=True, verbose_name='основание для исключения из реестра'),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='management_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='lата начала осуществления деятельности по управлению МКД'),
        ),
        migrations.AddField(
            model_name='house',
            name='agr_conclusion_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата заключения договора'),
        ),
        migrations.AddField(
            model_name='house',
            name='changing_doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='основание для изменения: дата документа'),
        ),
        migrations.AddField(
            model_name='house',
            name='changing_doc_header',
            field=models.CharField(max_length=500, null=True, verbose_name='основание для изменения: заголовок документа'),
        ),
        migrations.AddField(
            model_name='house',
            name='changing_doc_number',
            field=models.CharField(max_length=500, null=True, verbose_name='основание для изменения: номер документа'),
        ),
        migrations.AddField(
            model_name='house',
            name='changing_org_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата смены организации в реестре'),
        ),
        migrations.AddField(
            model_name='house',
            name='exclusion_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата исключения из реестра'),
        ),
        migrations.AddField(
            model_name='house',
            name='exclusion_legal_basis',
            field=models.CharField(max_length=500, null=True, verbose_name='основание для исключения из реестра'),
        ),
        migrations.AddField(
            model_name='house',
            name='management_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='lата начала осуществления деятельности по управлению МКД'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='building_year',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='год постройки'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='living_area',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='общая площадь жилых помещений'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='non_living_area',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='общая площадь нежилых помещений'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='number_of_apartments',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество квартир'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='total_area',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='общая площадь'),
        ),
        migrations.AlterField(
            model_name='house',
            name='building_year',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='год постройки'),
        ),
        migrations.AlterField(
            model_name='house',
            name='living_area',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='общая площадь жилых помещений'),
        ),
        migrations.AlterField(
            model_name='house',
            name='non_living_area',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='общая площадь нежилых помещений'),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_apartments',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество квартир'),
        ),
        migrations.AlterField(
            model_name='house',
            name='total_area',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='общая площадь'),
        ),
    ]
