# Generated by Django 2.1.4 on 2019-02-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0013_auto_20190215_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouse',
            name='exclusion_legal_basis',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='основание для исключения из реестра'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='inn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='kpp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='house',
            name='exclusion_legal_basis',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='основание для исключения из реестра'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ОГРН'),
        ),
    ]
