# Generated by Django 2.1.4 on 2019-03-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    def get_short_name(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        User = apps.get_model('dictionaries', 'user')
        for person in User.objects.all():
            name = person.name
            person.shortname = name.split(' ')[0] + ' ' + name.split(' ')[1][0] + '.' + name.split(' ')[2][0] + '.'
            person.save()

    dependencies = [
        ('dictionaries', '0015_department_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shortname',
            field=models.CharField(default='', max_length=200, verbose_name='ФИО (коротко)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='shortname',
            field=models.CharField(max_length=200, verbose_name='отдел (коротко)'),
        ),
        migrations.RunPython(get_short_name),
    ]
