# Generated by Django 2.1.4 on 2019-03-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0017_officer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officer',
            options={'verbose_name': 'Должностное лицо'},
        ),
    ]
