# Generated by Django 2.1.4 on 2019-04-11 07:09

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0019_auto_20190411_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(blank=True, to='dictionaries.File', verbose_name='файлы'),
        ),
        migrations.AlterField(
            model_name='document',
            name='houses',
            field=models.ManyToManyField(blank=True, to='dictionaries.House', verbose_name='адреса домов'),
        ),
        migrations.AlterField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dictionaries.Document'),
        ),
        migrations.AlterField(
            model_name='house',
            name='files',
            field=models.ManyToManyField(blank=True, to='dictionaries.File', verbose_name='файлы'),
        ),
        migrations.AlterField(
            model_name='house',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.Organization', verbose_name='Организация'),
        ),
    ]
