# Generated by Django 2.2 on 2019-04-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0022_auto_20190426_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='value',
            field=models.TextField(),
        ),
    ]
