# Generated by Django 2.2 on 2020-05-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0025_auto_20190605_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganization',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Наименование организации'),
        ),
    ]
