# Generated by Django 2.1.4 on 2019-01-17 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinspection',
            name='act_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата акта'),
        ),
        migrations.AlterField(
            model_name='historicalinspection',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='historicalinspection',
            name='date_begin',
            field=models.DateField(blank=True, null=True, verbose_name='начало проведения проверки'),
        ),
        migrations.AlterField(
            model_name='historicalinspection',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='окончание проведения проверки'),
        ),
        migrations.AlterField(
            model_name='historicalinspection',
            name='erp_number',
            field=models.TextField(blank=True, default='', verbose_name='номер в EРП'),
        ),
        migrations.AlterField(
            model_name='historicalinspection',
            name='gis_gkh_number',
            field=models.TextField(blank=True, default='', verbose_name='номер в ГИС ЖКХ'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='act_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата акта'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date_begin',
            field=models.DateField(blank=True, null=True, verbose_name='начало проведения проверки'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='окончание проведения проверки'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='erp_number',
            field=models.TextField(blank=True, default='', verbose_name='номер в EРП'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='gis_gkh_number',
            field=models.TextField(blank=True, default='', verbose_name='номер в ГИС ЖКХ'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.User', verbose_name='инспектор'),
        ),
    ]
