# Generated by Django 2.1.4 on 2019-01-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_auto_20190117_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinspection',
            name='violations_quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество нарушений'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='cancellation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.Cancellation', verbose_name='Информация об отмене результатов проверки'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='control_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.ControlForm', verbose_name='форма проверки'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='control_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.ControlKind', verbose_name='вид контроля'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='control_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.ControlPlan', verbose_name='вид проверки'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.InspectionResult', verbose_name='причина непроведения проверки'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_subjects',
            field=models.ManyToManyField(blank=True, to='inspections.InspectionSubject', verbose_name='предмет проверки'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_tasks',
            field=models.ManyToManyField(blank=True, to='inspections.InspectionTask', verbose_name='задачи проверки'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='legal_basis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.LegalBasis', verbose_name='основание для проверки'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='violations_quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество нарушений'),
        ),
    ]
