# Generated by Django 2.1.4 on 2019-01-24 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionaries', '0003_auto_20190124_1419'),
        ('inspections', '0004_auto_20190124_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrecept',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=500, verbose_name='номер документа')),
                ('doc_date', models.DateField(blank=True, verbose_name='дата документа')),
                ('doc_type', models.CharField(default='', max_length=500, null=True, verbose_name='тип документа')),
                ('root_id', models.IntegerField(default=0, editable=False, verbose_name='root_id')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('precept_begin_date', models.DateField(null=True, verbose_name='дата начала исполнения предписания')),
                ('precept_end_date', models.DateField(null=True, verbose_name='дата окончания исполнения предписания')),
                ('prolongation_date', models.DateField(null=True, verbose_name='дата окончания исполнения предписания с продлением')),
                ('comment', models.TextField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('document_ptr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Document')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Organization')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Document')),
            ],
            options={
                'verbose_name': 'historical Предписание',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Precept',
        ),
        migrations.RenameModel(
            old_name='OrderResult',
            new_name='PreceptResult',
        ),
        migrations.RenameModel(
            old_name='OrderStatus',
            new_name='PreceptStatus',
        ),
        migrations.RenameModel(
            old_name='ViolationInOrder',
            new_name='ViolationInPrecept',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='document_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='order_result',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='parent',
        ),
        migrations.RenameField(
            model_name='precept',
            old_name='order_begin_date',
            new_name='precept_begin_date',
        ),
        migrations.RenameField(
            model_name='precept',
            old_name='order_end_date',
            new_name='precept_end_date',
        ),
        migrations.RenameField(
            model_name='precept',
            old_name='order_result',
            new_name='precept_result',
        ),
        migrations.RenameField(
            model_name='violationinprecept',
            old_name='order',
            new_name='precept',
        ),
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
        migrations.AddField(
            model_name='historicalprecept',
            name='precept_result',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inspections.PreceptResult'),
        ),
    ]
