# Generated by Django 2.1.4 on 2019-01-28 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_auto_20190124_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprecept',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalprecept',
            name='precept_begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата начала исполнения предписания'),
        ),
        migrations.AlterField(
            model_name='historicalprecept',
            name='precept_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания исполнения предписания'),
        ),
        migrations.AlterField(
            model_name='historicalprecept',
            name='prolongation_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания исполнения предписания с продлением'),
        ),
        migrations.AlterField(
            model_name='precept',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='precept',
            name='precept_begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата начала исполнения предписания'),
        ),
        migrations.AlterField(
            model_name='precept',
            name='precept_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания исполнения предписания'),
        ),
        migrations.AlterField(
            model_name='precept',
            name='precept_result',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.PreceptResult', verbose_name='результат предписания'),
        ),
        migrations.AlterField(
            model_name='precept',
            name='prolongation_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания исполнения предписания с продлением'),
        ),
    ]
