# Generated by Django 2.1.4 on 2019-02-05 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_auto_20190202_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprecept',
            name='precept_result',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inspections.PreceptResult', verbose_name='результат предписания'),
        ),
        migrations.AlterField(
            model_name='precept',
            name='precept_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.PreceptResult', verbose_name='результат предписания'),
        ),
    ]
