# Generated by Django 2.1.4 on 2019-03-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_auto_20190205_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violationininspection',
            options={'verbose_name': 'Выявленные нарушения'},
        ),
        migrations.AlterModelOptions(
            name='violationinprecept',
            options={'verbose_name': 'Нарушения в предписании'},
        ),
    ]
