# Generated by Django 2.2 on 2019-05-24 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def populate_inspection_types(apps, schema_editor):
        InspectionType = apps.get_model('inspections', 'inspectiontype')
        InspectionType(text='Первичная').save()
        InspectionType(text='Проверка исполнения предписания').save()

    def get_inspection_type(apps, schema_editor):
        Inspection = apps.get_model('inspections', 'inspection')
        InspectionType = apps.get_model('inspections', 'inspectiontype')
        for insp in Inspection.objects.all():
            type = 'Проверка исполнения предписания' if insp.parent else 'Первичная'
            insp.inspection_type = InspectionType.objects.get(text=type)
            insp.save()

    def update_users_column_order(apps, schema_editor):
        Preference = apps.get_model('dictionaries', 'preference')
        for pref in Preference.objects.filter(target='inspections_table', variable='columns_order'):
            pref.value = pref.value.replace(',type,', ',inspection_type__text,')
            pref.save()
    dependencies = [
        ('inspections', '0013_auto_20190430_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicalinspection',
            name='inspection_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inspections.InspectionType', verbose_name='тип проверки'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.InspectionType', verbose_name='тип проверки'),
        ),
        migrations.RunPython(populate_inspection_types),
        migrations.RunPython(get_inspection_type),
        migrations.RunPython(update_users_column_order),
    ]
