# Generated by Django 2.2 on 2019-05-31 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def get_inspection_department(apps, schema_editor):
        Inspection = apps.get_model('inspections', 'inspection')
        for insp in Inspection.objects.all():
            if insp.inspector:
                insp.department = insp.inspector.department
                insp.save()
    dependencies = [
        ('dictionaries', '0024_auto_20190429_1107'),
        ('inspections', '0014_auto_20190524_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinspection',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionaries.Department', verbose_name='отдел'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.Department', verbose_name='отдел'),
        ),
        migrations.RunPython(get_inspection_department),
    ]
