# Generated by Django 2.2 on 2019-10-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_auto_20190531_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinspection',
            name='RPN_notification',
            field=models.TextField(blank=True, null=True, verbose_name='информация о направлении в Роспотребнадзор'),
        ),
        migrations.AddField(
            model_name='historicalinspection',
            name='no_preception_needed',
            field=models.BooleanField(default=False, verbose_name='Предписание не требуется'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='RPN_notification',
            field=models.TextField(blank=True, null=True, verbose_name='информация о направлении в Роспотребнадзор'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='no_preception_needed',
            field=models.BooleanField(default=False, verbose_name='Предписание не требуется'),
        ),
    ]
