# Generated by Django 2.2 on 2019-10-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_auto_20191028_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinspection',
            name='RPN_notification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='информация о направлении в Роспотребнадзор'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='RPN_notification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='информация о направлении в Роспотребнадзор'),
        ),
    ]
