# Generated by Django 2.2 on 2019-11-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_auto_20191028_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprecept',
            name='recalculation',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма перерасчета'),
        ),
        migrations.AddField(
            model_name='precept',
            name='recalculation',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма перерасчета'),
        ),
    ]
